"""Voice-conditioning format constants shared by training and inference."""

SPEAKER_CONDITIONING_VERSION = 1
SPEAKER_PATCH_LAYOUT_VERSION = 2
CROSS_LINGUAL_CAPABILITY_VERSION = 1

__all__ = [
    "CROSS_LINGUAL_CAPABILITY_VERSION",
    "SPEAKER_CONDITIONING_VERSION",
    "SPEAKER_PATCH_LAYOUT_VERSION",
]
