"""Voice-conditioning format constants shared by training and inference."""

DEFAULT_MAX_REFERENCE_SECONDS = 12.0
SPEAKER_CONDITIONING_VERSION = 1
SPEAKER_PATCH_LAYOUT_VERSION = 2
CROSS_LINGUAL_CAPABILITY_VERSION = 2

__all__ = [
    "CROSS_LINGUAL_CAPABILITY_VERSION",
    "DEFAULT_MAX_REFERENCE_SECONDS",
    "SPEAKER_CONDITIONING_VERSION",
    "SPEAKER_PATCH_LAYOUT_VERSION",
]
