"""Post-training primitives for NAR-VAE flow models."""

from vyvotts.post_training.grpo import (
    EventReduction,
    FlowGRPOConfig,
    FlowGRPOMetrics,
    FlowGRPOTrainer,
    FlowGRPOTrajectory,
    clipped_grpo_loss,
    combine_reward_components,
    diagonal_gaussian_log_prob,
    flow_sde_transition,
    group_relative_advantages,
    recompute_transition_statistics,
    same_variance_gaussian_kl,
    sample_flow_grpo_trajectory,
)
from vyvotts.post_training.nar_vae_stage import (
    DEFAULT_GRPO_CONFIG_PATH,
    NARVAEGRPOCollator,
    bind_reward_evaluator_manifest,
    build_nar_vae_grpo_runtime,
    grpo_post_train,
    model_export_config_from_manifest,
)
from vyvotts.post_training.stage import (
    GRPOPreparedBatch,
    GRPOStageConfig,
    GRPOStageError,
    GRPOStageRuntime,
    RankPromptSampler,
    grpo_reference_identity,
    load_grpo_stage_config,
    reduce_grpo_metrics,
    run_grpo_stage,
    validate_prompt_group_dataset,
)

__all__ = [
    "DEFAULT_GRPO_CONFIG_PATH",
    "EventReduction",
    "FlowGRPOConfig",
    "FlowGRPOMetrics",
    "FlowGRPOTrainer",
    "FlowGRPOTrajectory",
    "GRPOPreparedBatch",
    "GRPOStageConfig",
    "GRPOStageError",
    "GRPOStageRuntime",
    "NARVAEGRPOCollator",
    "RankPromptSampler",
    "bind_reward_evaluator_manifest",
    "build_nar_vae_grpo_runtime",
    "clipped_grpo_loss",
    "combine_reward_components",
    "diagonal_gaussian_log_prob",
    "flow_sde_transition",
    "group_relative_advantages",
    "grpo_post_train",
    "grpo_reference_identity",
    "load_grpo_stage_config",
    "model_export_config_from_manifest",
    "reduce_grpo_metrics",
    "recompute_transition_statistics",
    "same_variance_gaussian_kl",
    "sample_flow_grpo_trajectory",
    "run_grpo_stage",
    "validate_prompt_group_dataset",
]
